language: rust
rust:
  - stable
  - beta
  - nightly
# dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
env:
  - PATH=$HOME/.cargo/bin:$PATH
before_script:
  - cargo install cargo-travis -f
  - rustup toolchain install nightly
  - rustup component add --toolchain nightly rustfmt-preview
  - cargo +nightly install --force rustfmt-nightly
script:
  - echo "Checking Gotham codebase with rustfmt release `cargo +nightly fmt --version`."
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo test --all --features ci
after_success:
  - cargo coveralls
matrix:
  allow_failures:
    - rust: nightly
